### ISSUE TITLE
all-in-one: support ARM

### ISSUE THREAD

**Issue by liangye20** [wey-gu/nebula-up#18]
机器为m1 mac，一直装不上去，请问是什么原因？

**Comment by wey-gu** [comment]
抱歉，暂时 all in one 全家桶只支持 Linux 😭， m1 大多数情况下需要 arm 镜像的容器才行，我还没花时间去支持。

**Comment by wey-gu** [comment]
@liangye20 我觉得现在 all-in-one 虽然不全是 arm ，但是其他的模拟应该也是可用状态的了可以试试，我先关掉了。
