### ISSUE TITLE
pyspark的例子可以跑通但通过 spark-submit 提交任务就报错

### ISSUE THREAD

**Issue by liangye20** [wey-gu/nebula-up#19]
`➜  ~ ~/.nebula-up/load-LiveJournal-dataset.sh
Password:
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2022/06/18 03:49:05 --- START OF NEBULA IMPORTER ---
2022/06/18 03:49:17 [INFO] clientmgr.go:31: Create 1 Nebula Graph clients
2022/06/18 03:49:17 [INFO] reader.go:49: The delimiter of /root/soc-LiveJournal1.txt is U+0009
2022/06/18 03:49:17 [INFO] reader.go:68: Start to read file(0): /root/soc-LiveJournal1.txt, schema: < :VID(int) >
2022/06/18 03:49:17 [INFO] reader.go:49: The delimiter of /root/soc-LiveJournal1.txt is U+0009
2022/06/18 03:49:17 [INFO] reader.go:68: Start to read file(1): /root/soc-LiveJournal1.txt, schema: < :IGNORE,:VID(int) >
panic: runtime error: index out of range [1] with length 1

goroutine 12 [running]:
github.com/vesoft-inc/nebula-importer/pkg/reader.(*BatchMgr).Add(0xc0001145a0, 0x1, 0xc00023a0b0, 0x1, 0x1, 0x56, 0xc000096130, 0x0, 0x0)
	/home/nebula-importer/pkg/reader/batchmgr.go:207 +0x17a
github.com/vesoft-inc/nebula-importer/pkg/reader.(*FileReader).Read(0xc000116280, 0x0, 0x0, 0x0)
	/home/nebula-importer/pkg/reader/reader.go:163 +0x643
github.com/vesoft-inc/nebula-importer/pkg/cmd.(*Runner).Run.func2(0xc0001048c0, 0xc00008ca40, 0xc000116280, 0xc000095700, 0x1a)
	/home/nebula-importer/pkg/cmd/runner.go:74 +0x40
created by github.com/vesoft-inc/nebula-importer/pkg/cmd.(*Runner).Run
	/home/nebula-importer/pkg/cmd/runner.go:73 +0x79a`

**Comment by wey-gu** [comment]
我回头看看哈，刚好我也是 m1，之前都是在 amd64 Linux 上测试的。

**Comment by wey-gu** [comment]
上边的报错是 importer 的错误，能说一下你具体做了啥，卡在哪里么？

**Comment by wey-gu** [comment]
closing as it's been a while without response/reproduction
