### ISSUE TITLE
windows 11 nebula dashboard docker-compose up failed

### ISSUE THREAD

**Issue by utopianet** [wey-gu/nebula-up#21]
(base) PS E:\GitHub\nebula\nebula-up\dashboard> docker-compose up
time="2022-07-10T19:34:15+08:00" level=warning msg="The \"PWD\" variable is not set. Defaulting to a blank string."

dashboard-nebula-stats-exporter-1  | F0710 11:34:34.907107       1 main.go:93] read config file failed: read /config.yaml: is a directory
Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:75: mounting "/prometheus.yaml" to rootfs at "/etc/prometheus/prometheus.yml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by wey-gu** [comment]
Thanks!
