### ISSUE TITLE
the v2.6.0 code should use Docker Desktop 4.2.0, to avoid graphd install problem...

### ISSUE THREAD

**Issue by mathlpz** [wey-gu/nebula-up#4]
the version of v2.6.0 nebula-docker-compose code, should use Docker Desktop <= 4.2.0, to avoid graphd install problem...

**Comment by mathlpz** [comment]
mark a problem.

**Comment by wey-gu** [comment]
Thanks a lot @mathlpz :)

**Comment by wey-gu** [comment]
ref: https://github.com/vesoft-inc/nebula/issues/3278
